Cambiada version del artifaact

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -39,10 +39,10 @@ jobs:
       - name: Run tests with coverage report
         working-directory: BackEnd
         run: |
-          pytest --cov=src --cov-report=xml --cov-report=term-missing tests/
+          pytest --cov=src --cov-report=xml:BackEnd/coverage.xml --cov-report=term-missing tests/
 
-      - name: List coverage files
-        run: ls -lh BackEnd/
+      - name: Verify coverage report
+        run: test -f BackEnd/coverage.xml || echo "Coverage report not found" && exit 1
 
       - name: Upload coverage report
         uses: actions/upload-artifact@v3
